services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../../src/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ../../src/grafana/config/datasource.json:/etc/grafana/provisioning/datasources/datasource.json
      - ../../src/grafana/config/grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - ../../src/grafana/config/grafana.ini
    expose:
      - 3000
    depends_on:
      - prometheus
    networks:
      - app_network

volumes:
  prometheus_data:
  grafana_data: