services:
  nginx-proxy:
    image: nginx:latest
    volumes:
      - ../../src/nginx/config/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django-app
      - airflow-webserver 
      - streamlit-app
      - prometheus
      - grafana
    networks:
      - app_network
