x-airflow-common: &airflow-common
  build:
    context: ../../src/airflow
    dockerfile: Dockerfile
    args:
      - HOST_UID=1000
  image: airflow-app:latest
  env_file:
    - ../../src/airflow/config/.env
    - ../../src/db/config/gold.conf  
  volumes:
    - ../../data:/opt/airflow/data
    - ../../src/airflow/dags:/opt/airflow/dags
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - app_network

services:
  airflow-db:
    image: postgres:13
    env_file:
      - ../../src/airflow/config/airflow-db.conf
    volumes:
      - airflow_metadata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - app_network

  airflow-webserver:
    <<: *airflow-common
    command: bash -c "airflow webserver"
    expose:
      - 8080
    depends_on:
      - airflow-db

  airflow-scheduler:
    <<: *airflow-common
    command: bash -c "airflow scheduler"
    depends_on:
      - airflow-db

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
        airflow db migrate &&
        airflow connections create-default-connections &&
        airflow connections add postgres_gold \\
          --conn-uri \"postgres://\$POSTGRES_USER:\$POSTGRES_PASSWORD@\$GOLD_SQL_HOST:\$SQL_PORT/\$POSTGRES_DB\" &&
        airflow users create \\
          --username \$ADMIN_USERNAME \\
          --password \$ADMIN_PASSWORD \\
          --firstname \$ADMIN_FIRSTNAME \\
          --lastname \$ADMIN_LASTNAME \\
          --role Admin \\
          --email \$ADMIN_MAIL"

    depends_on:
      - airflow-db
      - postgres-gold

volumes:
  airflow_metadata:

networks:
  app_network:
