services:
  streamlit-app:
    build:
      context: ../../src/streamlit
      dockerfile: Dockerfile
    image: streamlit-app:latest
    volumes:
      - ../../src/streamlit/app:/app
    env_file:
      - ../../src/streamlit/config/streamlit.conf
      - ../../src/django/config/databases/gold.conf
    expose:
      - 8501
    command: streamlit run /app/app.py
    depends_on:
      postgres-gold:
        condition: service_healthy
    networks:
      - app_network