services:
  postgres-gold:
    image: postgres:15
    container_name: cf-postgres-gold
    volumes:
      - postgres_data_gold:/var/lib/postgresql/data/
    env_file:
      - ../../src/db/config/gold.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  postgres_data_gold: