services:
  nginx-proxy:
    image: nginx:latest
    volumes:
      - ../../src/nginx/config/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - airflow-webserver 

    networks:
      - app_network
