services:
  airflow-db:
    image: postgres:13
    env_file:
      - ../config/airflow-db.conf
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  airflow-webserver:
    image: apache/airflow:2.10.3
    env_file:
      - ../config/airflow-db.conf
      - ../config/airflow.conf
    volumes:
      - ../src/airflow/dags:/opt/airflow/dags
      - ../src/airflow/logs:/opt/airflow/logs
      - ../src/airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    command: bash -c  "airflow webserver"
    depends_on:
      - airflow-db
      - airflow-init
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.10.3
    env_file:
      - ../config/airflow-db.conf
      - ../config/airflow.conf
    volumes:
      - ../src/airflow/dags:/opt/airflow/dags
      - ../src/airflow/logs:/opt/airflow/logs
      - ../src/airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c "airflow scheduler"
    depends_on:
      - airflow-db
      - airflow-init
    restart: always

  airflow-init:
    image: apache/airflow:2.10.3
    env_file:
      - ../config/airflow-db.conf
      - ../config/airflow.conf
    volumes:
      - ../src/airflow/dags:/opt/airflow/dags
      - ../src/airflow/logs:/opt/airflow/logs
      - ../src/airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c " airflow db init &&
                airflow db migrate &&
                airflow users create \\
                 --username admin \\
                 --password admin \\
                 --firstname admin \\
                 --lastname admin \\
                 --role Admin \\
                 --email admin@example.com"
    depends_on:
      - airflow-db

volumes:
  postgres-db-volume:
