# Jekyll configuration for Datafoundry documentation site

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme


# Site settings
title: ""
description: "Official documentation for the DataFoundry project."
logo: "/assets/img/DataFoundry.png"
show_downloads: true
url: "https://leobitto.github.io"
baseurl: "/DataFoundry" # Base URL for the project

# Exclude specific files or directories from being processed by Jekyll
exclude:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md

# Permalinks configuration
permalink: pretty

# Markdown and syntax highlighting settings
markdown: kramdown
highlighter: rouge

# GitHub Pages settings
github:
  is_project_page: true
  project_tagline: "Datafoundry: Modular ecosystem for SMEs"

# Collections
collections:
  docs:
    output: true
    permalink: /:path/:basename:output_ext

# Default layout for all files
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Pagination settings
paginate: 10
paginate_path: "/page:num/"
