name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest
      services:
        - name: docker:19.03.12
          image: docker:19.03.12
          options: --privileged
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Set up Docker
          uses: docker/setup-buildx-action@v2
  
        - name: Build and run tests
          run: |
            docker-compose -f docker/docker-compose.dev.yml up test-runner
  