name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: source manager.sh build

      - name: Verify Docker image creation
        run: docker images

      - name: Set lower case owner and repo names
        run: |
          echo "REPO_NAME_LC=${{ github.repository }}" >>${GITHUB_ENV}

      - name: Tag and push images
        run: |
          # Tag each service
          docker tag django-app:latest ${{ env.REGISTRY }}/${REPO_NAME_LC,,}-django:latest
          docker tag streamlit-app:latest ${{ env.REGISTRY }}/${REPO_NAME_LC,,}-streamlit:latest
          docker tag airflow-app:latest ${{ env.REGISTRY }}/${REPO_NAME_LC,,}-airflow:latest
          
      - name: Verify image creation
        run: |
          # verify image creation
          docker images

      - name: Push images to GHCR
        run: |
          # Push each service
          docker push ${{ env.REGISTRY }}/${REPO_NAME_LC,,}:/django-app:latest
          docker push ${{ env.REGISTRY }}/${REPO_NAME_LC,,}:/streamlit-app:latest
          docker push ${{ env.REGISTRY }}/${REPO_NAME_LC,,}:/airflow:latest